#pragma once

#define _CRT_SECURE_NO_WARNINGS
#define _WINSOCK_DEPRECATED_NO_WARNINGS
#define ERROR_CODE -1
#define NUM_OF_WORKER_THREADS 2
#define SUCCES_CODE 0
#define MAX_LOOPS 5 
#define MAX_NAME_LEN 20

#define MAX_LEN_OF_MESSAGE 1024
#define MAX_LEN_OF_LINE 256

#define CLIENT_REQUEST "CLIENT_REQUEST",
#define CLIENT_VERSUS "CLIENT_VERSUS_MSG",
#define CLIENT_REPLAY "CLIENT_REPLAY",
#define CLIENT_PLAYER_MOVE "CLIENT_PLAYER_MOVE"

#define SERVER_APPROVED "SERVER_APPROVED"
#define SERVER_INVITE "SERVER_INVITE"
#define SERVER_PLAYER_MOVE_REQUEST "SERVER_PLAYER_MOVE_REQUEST"
#define SERVER_GAME_RESULT "SERVER_GAME_RESULT"
#define SERVER__GAME_OVER_MENU "SERVER__GAME_OVER_MENU"

#define VERSUS_F 1
#define CPU_F -1



#define STRINGS_ARE_EQUAL( Str1, Str2 ) ( strcmp( (Str1), (Str2) ) == 0 )
